// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRDxl-8t3pwz0qChwMfy8WMwNlmnW2Pc',
    appId: '1:824420674681:web:98384baa114a09b745f8a8',
    messagingSenderId: '824420674681',
    projectId: 'vesthub-e465f',
    authDomain: 'vesthub-e465f.firebaseapp.com',
    storageBucket: 'vesthub-e465f.firebasestorage.app',
    measurementId: 'G-8DHG2F2HLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOHW1yaUZIzN2THtDMOQKzgWL1l6AIPPE',
    appId: '1:824420674681:android:014215524d61786e45f8a8',
    messagingSenderId: '824420674681',
    projectId: 'vesthub-e465f',
    storageBucket: 'vesthub-e465f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpl1uBNcvf2zKLCIa_Kz9Pt1HnG7_AH_8',
    appId: '1:824420674681:ios:38ca668ead51a54645f8a8',
    messagingSenderId: '824420674681',
    projectId: 'vesthub-e465f',
    storageBucket: 'vesthub-e465f.firebasestorage.app',
    iosBundleId: 'com.example.vesthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpl1uBNcvf2zKLCIa_Kz9Pt1HnG7_AH_8',
    appId: '1:824420674681:ios:38ca668ead51a54645f8a8',
    messagingSenderId: '824420674681',
    projectId: 'vesthub-e465f',
    storageBucket: 'vesthub-e465f.firebasestorage.app',
    iosBundleId: 'com.example.vesthub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrRDxl-8t3pwz0qChwMfy8WMwNlmnW2Pc',
    appId: '1:824420674681:web:b77daeca07a74d6345f8a8',
    messagingSenderId: '824420674681',
    projectId: 'vesthub-e465f',
    authDomain: 'vesthub-e465f.firebaseapp.com',
    storageBucket: 'vesthub-e465f.firebasestorage.app',
    measurementId: 'G-R5T1EZHK8L',
  );

}